#!/bin/bash

read -r -p "PostgreSQL user (default: postgres): " PG_USER
if [ "${PG_USER}" == "" ]
then
  PG_USER=postgres
fi

read -r -p "PostgreSQL password: " PG_PASS
if [ "${PG_PASS}" == "" ]
then
  echo "Error: PostgreSQL password must be specify"
  exit 1
fi

read -r -p "PostgreSQL host: " PG_HOST
if [ "${PG_HOST}" == "" ]
then
  echo "Error: PostgreSQL host must be specify"
  exit 1
fi

read -r -p "PostgreSQL port (default: 5432): " PG_PORT
if [ "${PG_PORT}" == "" ]
then
  PG_PORT=5432
fi

read -r -p "PostgreSQL db name (default: vknews): " PG_NAME
if [ "${PG_NAME}" == "" ]
then
  PG_NAME=vknews
fi

cat > deploy/entrypoint <<- EOM
#!/bin/bash

cd /usr/share/python3
. /usr/share/python3/venv/bin/activate

export PG_USER=${PG_USER}
export PG_PASS=${PG_PASS}
export PG_HOST=${PG_HOST}
export PG_PORT=${PG_PORT}
export PG_NAME=${PG_NAME}

cd vk-news-dashboard
gunicorn wsgi:server -b 0.0.0.0:5000
EOM

