#!/bin/bash

cd /usr/share/python3
. /usr/share/python3/venv/bin/activate

export PG_USER=postgres
export PG_PASS=password
export PG_HOST=postgres
export PG_PORT=5432
export PG_NAME=vknews

python vk-news-dashboard/run.py
